GET http://localhost:8080/lancamentos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjEyNTkxNDcsInVzZXJfbmFtZSI6ImFkbWluQG1haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiQ0FEQVNUUkFSX0xBTkNBTUVOVE8iLCJQRVNRVUlTQVJfQ0FURUdPUklBIiwiUEVTUVVJU0FSX1BFU1NPQSIsIlJFTU9WRVJfUEVTU09BIiwiUEVTUVVJU0FSX0xBTkNBTUVOVE8iLCJDQURBU1RSQVJfQ0FURUdPUklBIiwiQ0FEQVNUUkFSX1BFU1NPQSIsIlJFTU9WRVJfQ0FURUdPUklBIiwiUkVNT1ZFUl9MQU5DQU1FTlRPIl0sImp0aSI6IjRmMGFiZDY4LTA0NjEtNDhmNy1hZDNkLTRkOTY4YzllYWFjZiIsImNsaWVudF9pZCI6IndlYiIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.9TP_qW74HaEQXvpGUTIr2OsF-TS0M5kaztZNBZjYosM
###

GET http://localhost:8080/lancamentos/1 HTTP/1.1
Authorization: Basic admin admin

###

GET http://localhost:8080/lancamentos?size=3&pega=1 HTTP/1.1

###

POST http://loalhost/lancamento HTTP/1.1
Content-Type: : application/json

{
    "version": 0,
    "descricao": "Nova",
    "dataVencimento": "2017-06-10",
    "dataPagamento": null,
    "valor": 10.2,
    "observacao": "Muit",
    "pessoa": {
        "id": 2
    },
    "tipo": "DESPESA",
    "categoria": {
        "id": 1
    }
}

###

PATCH  http://loalhost/lancamento/16 HTTP/1.1
Content-Type: application/json

[
	{ "op": "replace", "path": "/dataPagamento", "value": "2018-01-10" }
]
