POST http://localhost:8080/oauth/token HTTP/1.1
Authorization: Basic angular api_key
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username=admin
&password=admin

###

POST http://localhost:8080/oauth/token HTTP/1.1
Authorization: Basic angular api_key
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJhdGkiOiIyNzIxNGQ2My00NDZlLTQ5MmEtYjNmYy1hZjdlOTMyNGYwN2MiLCJleHAiOjE1NjA3OTg5MzUsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiJkZGNiOGJjMy1lZjZjLTQ0ZDItYWI0Mi00OTVjZTJjOGYxOWUiLCJjbGllbnRfaWQiOiJhbmd1bGFyIn0._9JXLCngCo2h7wE5dpi7WB4WnBJyPDCKgCIdttJJAXQ
###

POST http://localhost:8080/oauth/token HTTP/1.1
Authorization: Basic angular api_key
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token


###

GET http://localhost:8080/lancamentos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjEwNjkyMDEsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjA2ZWEwN2I4LTM0MmEtNGQ3MS05ODFmLWM0ZGI3YzViMmU1NyIsImNsaWVudF9pZCI6ImFuZ3VsYXIiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.zOdRVVvM-pVJlKRSekfDs8Z6Dlvc7h1nv62X3F6GZds

###

GET http://localhost:8080/lancamentos/1 HTTP/1.1
Authorization: Basic admin admin

###

GET http://localhost:8080/lancamentos?size=3&pega=1 HTTP/1.1

###

POST http://loalhost/lancamento HTTP/1.1
Content-Type: : application/json

{
    "version": 0,
    "descricao": "Nova",
    "dataVencimento": "2017-06-10",
    "dataPagamento": null,
    "valor": 10.2,
    "observacao": "Muit",
    "pessoa": {
        "id": 2
    },
    "tipo": "DESPESA",
    "categoria": {
        "id": 1
    }
}

###

PATCH  http://loalhost/lancamento/16 HTTP/1.1
Content-Type: application/json

[
	{ "op": "replace", "path": "/dataPagamento", "value": "2018-01-10" }
]
