GET http://localhost:8080/lancamentos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbkBtYWlsLmNvbSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJub21lIjoiQWRtaW5pc3RyYWRvciIsImV4cCI6MTU2MTMyMzYwOCwiYXV0aG9yaXRpZXMiOlsiQ0FEQVNUUkFSX0xBTkNBTUVOVE8iLCJQRVNRVUlTQVJfQ0FURUdPUklBIiwiUEVTUVVJU0FSX1BFU1NPQSIsIlJFTU9WRVJfUEVTU09BIiwiUEVTUVVJU0FSX0xBTkNBTUVOVE8iLCJDQURBU1RSQVJfQ0FURUdPUklBIiwiQ0FEQVNUUkFSX1BFU1NPQSIsIlJFTU9WRVJfQ0FURUdPUklBIiwiUkVNT1ZFUl9MQU5DQU1FTlRPIl0sImp0aSI6IjlhMjA3YzU0LWQ4MTYtNDNjMC05ZDVkLWYxZDQ0ZTBlYTRmMCIsImNsaWVudF9pZCI6IndlYiJ9.pdRtsCFAEvFkO5ESyonoHIyjViTn2yq0B68zg0tIvs8

###
GET http://localhost:8080/lancamentos?resumo&descricao=Salário  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbkBtYWlsLmNvbSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJub21lIjoiQWRtaW5pc3RyYWRvciIsImV4cCI6MTU2MTMyMzYwOCwiYXV0aG9yaXRpZXMiOlsiQ0FEQVNUUkFSX0xBTkNBTUVOVE8iLCJQRVNRVUlTQVJfQ0FURUdPUklBIiwiUEVTUVVJU0FSX1BFU1NPQSIsIlJFTU9WRVJfUEVTU09BIiwiUEVTUVVJU0FSX0xBTkNBTUVOVE8iLCJDQURBU1RSQVJfQ0FURUdPUklBIiwiQ0FEQVNUUkFSX1BFU1NPQSIsIlJFTU9WRVJfQ0FURUdPUklBIiwiUkVNT1ZFUl9MQU5DQU1FTlRPIl0sImp0aSI6IjlhMjA3YzU0LWQ4MTYtNDNjMC05ZDVkLWYxZDQ0ZTBlYTRmMCIsImNsaWVudF9pZCI6IndlYiJ9.pdRtsCFAEvFkO5ESyonoHIyjViTn2yq0B68zg0tIvs8

###
GET http://localhost:8080/lancamentos/1 HTTP/1.1
Authorization: Basic admin@mail.com 123456

###
GET http://localhost:8080/lancamentos?size=3&pega=1 HTTP/1.1

###
POST http://loalhost/lancamento HTTP/1.1
Content-Type: : application/json

{
    "version": 0,
    "descricao": "Nova",
    "dataVencimento": "2017-06-10",
    "dataPagamento": null,
    "valor": 10.2,
    "observacao": "Muit",
    "pessoa": {
        "id": 2
    },
    "tipo": "DESPESA",
    "categoria": {
        "id": 1
    }
}

###
PATCH  http://loalhost/lancamento/16 HTTP/1.1
Content-Type: application/json

[
	{ "op": "replace", "path": "/dataPagamento", "value": "2018-01-10" }
]
